name: release
on:
  push:
    tags:
    - v*

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3
          check-latest: true
          cache: true

      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REF: ${{ github.ref }}
        run: |
          export TAGNAME=`git describe --tags --abbrev=0`
          echo "========================================================="
          echo "DEBUG:" $REF
          echo "DEBUG:" $TAGNAME
          echo "DEBUG:" $PATH
          go env
          go install -v github.com/tcnksm/ghr@v0.14.0
          echo "========================================================="
          make dist
          echo "========================================================="
          echo "DEBUG: ls dist/"
          ls dist/
          echo "========================================================="
          ghr -n ${TAGNAME} -b "Release ${TAGNAME}" -prerelease ${TAGNAME} dist/

